services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python -m flask run --host=0.0.0.0 --port=5000 --debug
