services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python -m flask run --host=0.0.0.0 --port=5000 --debug

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: